s3_bucket_name = "woc-filevault-bucket"
ecr_repo_name   = "vault-app-repo"
terraform_admin_user_iam_name = "terraform-admin"
github_repo_url = "https://github.com/DanyaalZar-Solirius/filevault"
vpc_cidr = "10.0.0.0/16"
kubernetes_cluster_name = "vault-file-app-cluster"